apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stock-ui.fullname" . }}-config
data:
  MASSIVE_REST_BASE: {{ .Values.app.env.MASSIVE_REST_BASE | quote }}
  MASSIVE_MOCK: {{ .Values.app.env.MASSIVE_MOCK | quote }}
  K8S_NAMESPACE: {{ .Release.Namespace | quote }}
  SPARK_APP_NAME: "massive-aggregates-stream"
