apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stock-ui.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stock-ui.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "stock-ui.name" . }}
    spec:
      serviceAccountName: {{ include "stock-ui.fullname" . }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            #- name: DATABASE_URL
            #  value: >-
            #    postgresql+psycopg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}
            #    @{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
            - name: DATABASE_URL
              value: "postgresql+psycopg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
            - name: MASSIVE_REST_BASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stock-ui.fullname" . }}-config
                  key: MASSIVE_REST_BASE
            - name: MASSIVE_MOCK
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stock-ui.fullname" . }}-config
                  key: MASSIVE_MOCK
            - name: K8S_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stock-ui.fullname" . }}-config
                  key: K8S_NAMESPACE
            - name: SPARK_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stock-ui.fullname" . }}-config
                  key: SPARK_APP_NAME
            - name: MASSIVE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "stock-ui.fullname" . }}-secret
                  key: MASSIVE_API_KEY
          readinessProbe:
            httpGet: { path: /tickers, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /tickers, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
